version: '3.4'

services:
  deathmatch-sessions:
    image: ${DOCKER_REGISTRY-}deathmatchsessions
    build:
      context: .
      dockerfile: Api/Deathmatch-Sessions/Dockerfile
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqldb
    environment:
        - SA_PASSWORD=RaynorRaiders44
        - ACCEPT_EULA=Y
    ports:
        - "1440:1433"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo



